### ISSUE TITLE
Inconsistent tree

### ISSUE THREAD

**Issue by sergey-suloev** [sergey-senozhatsky/linux-next-ss#1]
*** Default configuration is based on 'defconfig'
fs/Kconfig:326: can't open file "fs/cifsd2/Kconfig"
scripts/kconfig/Makefile:81: recipe for target 'defconfig' failed
make[1]: *** [defconfig] Error 1
Makefile:538: recipe for target 'defconfig' failed
make: *** [defconfig] Error 2

**Comment by sergey-senozhatsky** [comment]
Whoa, didn't expect that anyone would want to build next-ss tree :)
Yeah, cifsd is simply a symlink on my dev box, because I sometimes
need to quickly build test it with -next, -vanila, -stable, etc. 
I'll drop the patch.

Thanks.

-ss

**Comment by sergey-suloev** [comment]
@sergey-senozhatsky 
thank you!
